language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: 
 - pytest
 - nosetests --with-coverage --cover-package=tests
after_success: 
 - coveralls
 - coverage report